[project]
name = "markitdown-uv"
version = "0.1.0"
description = "File to markitdown Converter"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "gunicorn>=23.0.0",
    "markitdown>=0.0.1a2",
    "uv>=0.5.9",
]
